[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests -Dmaven.compiler.source=21 -Dmaven.compiler.target=21"]

[phases.start]
cmd = "java -Xmx512m -jar target/*.jar"